### ISSUE TITLE
Project Review: Summary

### ISSUE THREAD

**Issue by SidTheEngineer** [Doxso88/prj-rev-bwfs-dasmoto#1]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4/4
* _Comment(s):_ CSS file is linked to the HTML appropriately.
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 2/4
* _Comment(s):_ The overall styling of the site is a bit off with respect to the design specification. Some of the main things we can improve here is making sure that all of the font throughout the page is Helvetica and making sure that the elements throughout each section are left aligned instead of center. One thing that is missing for me due to using absolute pathing is the background image for the header. We'll want to make sure we use a path to the image relative to the CSS file so that the image can display properly when used elsewhere.
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 3.5/4
* _Comment(s):_ Overall your HTML looks solid. Everything is structured/organized well and just about all elements are used appropriately (we should use `<span>` instead of `<a>` for the price text 😉). The only suggestion for improvement I have here is taking advantage of using classes when more than one element needs to be styled the same way. Id's should be reserved for identifying unique elements and classes for styling more than one element, such as your <a> tags.
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 3/4
* _Comment(s):_ As mentioned in the previous comment, we'll want to take advantage of using a class to style our price text so as to not have to repeat ourselves here in the CSS. Along with this, we'll want to make sure our elements are left aligned.

**Comment by Doxso88** [comment]
Awesome! Thanks so much for the feedback and I will use these tips going forward. The only comment i have for this is when I was styling it with the CSS i centered everything to showcase it in a more appealing way. I knew it wasn’t centered in the project just wanted to change it up. But as far as everything else goes, i really appreciate the feedback.
